### ISSUE TITLE
Wrong variable type in template

### ISSUE THREAD

**Issue by brow86** [voxpupuli/puppet-openssl#100]
On the following line there is a `$` when there should be a `@`.

https://github.com/camptocamp/puppet-openssl/blob/6060123d08656e78b300c1badba2bfec2c2ed01b/templates/cert.cnf.erb#L17

I forked the repo, updated it, and tested it after the change.  Works well.

**Comment by raphink** [comment]
Good catch. Can you open a PR please?

**Comment by makeacode** [comment]
we just got bit by this bug after upgrading our module to the 1.14.  can we get this merged please?

**Comment by makeacode** [comment]
no fix?

**Comment by raphink** [comment]
#101 has a fix for it, but needs rebasing.

**Comment by zilchms** [comment]
@brow86 same as with the PR :) do you want to close this?

**Comment by smortex** [comment]
Yeah, overcome by events. Closing.
