### ISSUE TITLE
openssl_version fact resolves to nil

### ISSUE THREAD

**Issue by storm49152** [voxpupuli/puppet-openssl#148]
- Puppet: 6.28.0
- Ruby: ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
- Distribution: Rocky Linux release 8.6
- Module version: 2.0.1

```shell
[root@server ~]# cat /etc/rocky-release
Rocky Linux release 8.6 (Green Obsidian)
[root@server ~]# facter -p openssl_version

[root@server ~]# openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

Using the regex found in the fact code:

```ruby
irb(main):001:0> a = 'OpenSSL 1.1.1k  FIPS 25 Mar 2021'
=> "OpenSSL 1.1.1k  FIPS 25 Mar 2021"
irb(main):002:0> b = %r{^OpenSSL ([\w.\-]+)( FIPS)?( +)([\d.]+)( +)([\w.]+)( +)([\d.]+)}.match(a)
=> nil
```
I did further testing, and it seems it starts failing at `[w.\-]`. To me, it doesn't look like `[\w.\-]+` will match `1.1.1k`, even though for some reason it does work on CentOS 7.9 with "OpenSSL 1.0.2k-fips".

For me, this seems work better:
(Focussing on the version substring and "fips" parts, with OpenSSL version strings found on Rocky Linux 8.6 and CentOS 7.9)

```ruby
irb(main):001:0> a = 'OpenSSL 1.1.1k  FIPS 25 Mar 2021'
=> "OpenSSL 1.1.1k  FIPS 25 Mar 2021"
irb(main):002:0> b = %r{ \d.\d.\d\w?([\s]+|\-)(fips|FIPS)?}.match(a)
=> #<MatchData " 1.1.1k  FIPS" 1:"  " 2:"FIPS">
irb(main):003:0> b[0].strip() if b
=> "1.1.1k  FIPS"

irb(main):011:0> c = 'OpenSSL 1.0.2k-fips  26 Jan 2017'
=> "OpenSSL 1.0.2k-fips  26 Jan 2017"
irb(main):012:0> d = %r{ \d.\d.\d\w?([\s]+|\-)(fips|FIPS)?}.match(c)
=> #<MatchData " 1.0.2k-fips" 1:"-" 2:"fips">
irb(main):013:0> d[0].strip() if d
=> "1.0.2k-fips"
```

I'm by no means a Ruby nor regex expert, and I'm only improvising with the regex currently present in the fact. Therefore, I'm hesitant to create a PR, because I'm unsure if it will work correctly in all cases. But, maybe this helps.

**Comment by kenyon** [comment]
This was fixed in #135.
