### ISSUE TITLE
r10k generate types fails

### ISSUE THREAD

**Issue by ncstate-daniel** [voxpupuli/puppet-openssl#197]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.7.0 (server 8.6.1)
- Ruby: 2.7.8
- Distribution: Rocky Linux 9
- Module version: 3.1.0

## How to reproduce (e.g Puppet code you use)

Doesn't show up in puppet code, shows up generate types runs as part of r10k.  On the puppetserver host run:
puppet generate types --environment production
 (or whatever environment you are using that's not production)
Note: You don't need r10k to be involved at all -- I just use it via r10k.  That command should work regardless.

## What are you seeing

Output from command is:
`Error: Failed to load custom type 'x509_cert' from '/etc/puppetlabs/code/environments/chass_master/modules/openssl/lib/puppet/type/x509_cert.rb': uninitialized constant Puppet::Parameter::Boolean`

## What behaviour did you expect instead

It not to do that and to properly generate the x509_cert resource type.  (shows up in .resource_types/x509_cert.pp if it generates correctly)  Output from generate types should be empty.

## Output log

`Error: Failed to load custom type 'x509_cert' from '/etc/puppetlabs/code/environments/chass_master/modules/openssl/lib/puppet/type/x509_cert.rb': uninitialized constant Puppet::Parameter::Boolean`

## Any additional information you'd like to impart

This is new as of me updating to the 3.x series of the module.

**Comment by ncstate-daniel** [comment]
I used a crappy hack to work around the issue for now:
https://github.com/ncstate-daniel/puppet-openssl/commit/5119b4f31a277d806a4d45ddab970b01a6559128

But of course that's not something I would turn into a PR as I don't know the intention there.

**Comment by alexjfisher** [comment]
> Puppet::Parameter::Boolean

The actual fix is probably just to add
`require 'puppet/parameter/boolean'` at the top of the file near the other `require` on line 3.  Would you be able to verify this and open a PR if it fixes the issue for you?

**Comment by ncstate-daniel** [comment]
That did indeed resolve the issue.  Issuing a PR one moment.
